Web/Controllers/OrdersController.cs
using Lib.Interfaces;
using Lib.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;
using Newtonsoft.Json;
using System.Fabric;
using static NuGet.Packaging.PackagingConstants;

namespace Web.Controllers
{
    public class OrdersController : Controller
    {
        public static OrderList ListOfElements = new OrderList();

        public async Task<IActionResult> History()
        {
            var fabricpaymentURI = new Uri("fabric:/Shop/Payment");

            FabricClient fabricClient = new FabricClient();
            var partitionsList = (await fabricClient.QueryManager.GetPartitionListAsync(fabricpaymentURI));
            int index = new Random().Next(0, partitionsList.Count);

            IPayment paymentProxy = null;
            var servicePartitionKey = new ServicePartitionKey(index % partitionsList.Count);
            paymentProxy = ServiceProxy.Create<IPayment>(fabricpaymentURI, servicePartitionKey); // Payment dictionary
            var orders = new List<Order>();

            List<string> ordersJSON = await paymentProxy.GetOrdersHistory();
            ordersJSON.ForEach(x => orders.Add(JsonConvert.DeserializeObject<Order>(x)!));


            List<OrderViewModel> ordersViewModelList = new List<OrderViewModel>();

            foreach (var order in orders)
            {
                List<Product> listOfProductsTemp = new List<Product>();

                foreach (var product in order.Products)
                {
                    listOfProductsTemp.Add(JsonConvert.DeserializeObject<Product>(product)!);
                }
                OrderViewModel orderViewModel = new OrderViewModel(order.Id, order.TimeOfOrder, order.Price, order.UserId, order.Address, listOfProductsTemp, false);
                ordersViewModelList.Add(orderViewModel);
            }

            return View(ordersViewModelList);
           // return Page.Response.Redirect(Page.Request.Url.ToString(), true);

        }

        //[HttpGet]
        //[Route("Orders/History")]
        //public IActionResult History()
        //{

        //    return View(ListOfElements);
        //}

        //[HttpPost]
        //[Route("Orders/Update")]
        //public IActionResult Update([FromBody]List<string> ordersJSON)
        //{
        //    if(ordersJSON!=null)
        //    {
        //        var orders = new List<Order>();

        //        ordersJSON.ForEach(x => orders.Add(JsonConvert.DeserializeObject<Order>(x)!));
        //        OrderList orderList = new OrderList(orders);
        //        ListOfElements = orderList;
        //    }


        //    return RedirectToAction("History", "Orders");
        //}


    }
}

Web/Controllers/PaypalController.cs
using Microsoft.AspNetCore.Mvc;
using Web.Models;

namespace Web.Controllers
{
    public class PaypalController : Controller
    {
        private readonly PaypalClient _paypalClient;

        public PaypalController(PaypalClient paypalClient)
        {
            this._paypalClient = paypalClient;
        }

        public IActionResult Index()
        {
            // ViewBag.ClientId is used to get the Paypal Checkout javascript SDK
            ViewBag.ClientId = _paypalClient.ClientId;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Order(CancellationToken cancellationToken)
        {
            try
            {
                // set the transaction price and currency
                var price = "100.00";
                var currency = "USD";

                // "reference" is the transaction key
                var reference = "INV001";

                var response = await _paypalClient.CreateOrder(price, currency, reference);

                return Ok(response);
            }
            catch (Exception e)
            {
                var error = new
                {
                    e.GetBaseException().Message
                };

                return BadRequest(error);
            }
        }

        public async Task<IActionResult> Capture(string orderId, CancellationToken cancellationToken)
        {
            try
            {
                var response = await _paypalClient.CaptureOrder(orderId);

                var reference = response.purchase_units[0].reference_id;

                // Put your logic to save the transaction here
                // You can use the "reference" variable as a transaction key

                return Ok(response);
            }
            catch (Exception e)
            {
                var error = new
                {
                    e.GetBaseException().Message
                };

                return BadRequest(error);
            }
        }

        public IActionResult Success()
        {
            return View();
        }
    
    }
}

Web/Controllers/ProductsController.cs
using Lib.Interfaces;
using Lib.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.ServiceFabric.Services.Client;
using Microsoft.ServiceFabric.Services.Remoting.Client;
using Newtonsoft.Json;
using System.Fabric;

namespace Web.Controllers
{
    public class ProductsController : Controller
    {
        public async Task<IActionResult> Catalog()
        {
            try
            {
                ICatalog proxy = ServiceProxy.Create<ICatalog>(new Uri("fabric:/Shop/ProductCatalog"));
                var products = new List<Product>();


                List<string> productsJson = await proxy.GetAllProducts();

                productsJson.ForEach(x => products.Add(JsonConvert.DeserializeObject<Product>(x)!));

                return View(products);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }

        }
       
        public async Task<IActionResult> Cart()
        {
            try
            {
                var fabricCartURI = new Uri("fabric:/Shop/Cart");

                FabricClient fabricClient = new FabricClient();
                var partitionsList = (await fabricClient.QueryManager.GetPartitionListAsync(fabricCartURI));
                int index = new Random().Next(0, partitionsList.Count);

                ICart cartProxy = null;

                var servicePartitionKey = new ServicePartitionKey(index);
                cartProxy = ServiceProxy.Create<ICart>(fabricCartURI, servicePartitionKey); // Basket dictionary

                var basket = new List<Product>();


                List<string> productsJson = await cartProxy.GetBasketProducts();

                productsJson.ForEach(x => basket.Add(JsonConvert.DeserializeObject<Product>(x)!));
                double totalPrice = 0;
                if(basket.Count > 0) { basket.ForEach(product => totalPrice += product.Price); }
                

                ViewBag.TotalPrice = totalPrice;

                return View(basket);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }

        }

        [HttpGet]
        public async Task<IActionResult> Buy(string id)
        {
            try
            {
                var fabricCartURI = new Uri("fabric:/Shop/Cart");

                FabricClient fabricClient = new FabricClient();
                var partitionsList = (await fabricClient.QueryManager.GetPartitionListAsync(fabricCartURI));
                int index = (id != null || id.Equals(string.Empty)) ? id.Count() :new Random().Next(0, partitionsList.Count);

                ICart cartProxy = null;

                var servicePartitionKey = new ServicePartitionKey(index % partitionsList.Count);
                cartProxy = ServiceProxy.Create<ICart>(fabricCartURI, servicePartitionKey); // Basket dictionary

                var basket = new List<Product>();


                await cartProxy.AddProductToBasketDictionary(id);

                return RedirectToAction("Cart");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }
        }

        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var fabricCartURI = new Uri("fabric:/Shop/Cart");

                FabricClient fabricClient = new FabricClient();
                var partitionsList = (await fabricClient.QueryManager.GetPartitionListAsync(fabricCartURI));
                int index = (id != null || id.Equals(string.Empty)) ? id.Count() : new Random().Next(0, partitionsList.Count);

                ICart cartProxy = null;

                var servicePartitionKey = new ServicePartitionKey(index % partitionsList.Count);
                cartProxy = ServiceProxy.Create<ICart>(fabricCartURI, servicePartitionKey); // Basket dictionary

                var basket = new List<Product>();

                await cartProxy.DeleteProductFromBasket(id);

                return RedirectToAction("Cart");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }
        }

        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                var fabricCartURI = new Uri("fabric:/Shop/Cart");

                FabricClient fabricClient = new FabricClient();
                var partitionsList = (await fabricClient.QueryManager.GetPartitionListAsync(fabricCartURI));
                int index = (id != null || id.Equals(string.Empty)) ? id.Count() : new Random().Next(0, partitionsList.Count);

                ICart cartProxy = null;

                var servicePartitionKey = new ServicePartitionKey(index % partitionsList.Count);
                cartProxy = ServiceProxy.Create<ICart>(fabricCartURI, servicePartitionKey); // Basket dictionary

                string product = await cartProxy.GetBasketProduct(id);

                return View(JsonConvert.DeserializeObject<Product>(product));
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }
        }
        public async Task<IActionResult> EditAction([FromForm]Product product)
        { 
            //Update product with Quanity
            try
            {
                var fabricCartURI = new Uri("fabric:/Shop/Cart");

                FabricClient fabricClient = new FabricClient();
                var partitionsList = (await fabricClient.QueryManager.GetPartitionListAsync(fabricCartURI));
                int index = (product.Id != null || product.Id.Equals(string.Empty)) ? product.Id.Count() : new Random().Next(0, partitionsList.Count);

                ICart cartProxy = null;

                var servicePartitionKey = new ServicePartitionKey(index % partitionsList.Count);
                cartProxy = ServiceProxy.Create<ICart>(fabricCartURI, servicePartitionKey); // Basket dictionary

                await cartProxy.EditProductInBasket(JsonConvert.SerializeObject(product));

                return RedirectToAction("Cart");
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }
        }

        public async Task<IActionResult> Search([FromForm]string productQuery)
        {
            try
            {
                ICatalog proxy = ServiceProxy.Create<ICatalog>(new Uri("fabric:/Shop/ProductCatalog"));
                var products = new List<Product>();

                List<string> productsJSON =await proxy.GetProductByFilter(productQuery);
                productsJSON.ForEach(x => products.Add(JsonConvert.DeserializeObject<Product>(x)!));

                return View("Catalog", products);
            }
            catch (Exception ex)
            {
                return StatusCode(500, "Error in communication with service " + ex.Message);
            }
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Web Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Catalog">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentification" asp-action="Users">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="History">History</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Authentification" asp-action="Logout">Log Out</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Paypal" asp-action="Index">Paypal</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Web - Cloud - MAS - 2024 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>